# Generated by Django 4.0.6 on 2022-11-19 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_img_hero_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
