# Generated by Django 4.0.6 on 2022-11-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_blog_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
