# Generated by Django 4.0.6 on 2022-11-23 07:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_portfolio_item_slider_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_item',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
