# Generated by Django 4.0.6 on 2022-11-23 13:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_portfolio_item_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_me',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
